### ISSUE TITLE
No COM port for BUMPY and Cannot get target remote

### ISSUE THREAD

**Issue by kautham** [electronut/ElectronutLabs-Bumpy#4]
I have been trying your tutorials with your [hackable ](https://www.tindie.com/products/ElectronutLabs/hackable-nordic-nrf52832-ble-development-kit/)kit in windows. I have done all the before steps correctly without any errors. But [after the step](https://github.com/electronut/ElectronutLabs-Bumpy#-using-bumpy-with-bluey-nordic-nrf52832) where i discover my target i could not work it out. In the Device manager bumpy is not creating any new COM ports. 
![capture](https://user-images.githubusercontent.com/17590053/40389500-45e5adea-5e30-11e8-81df-611204e2efa0.PNG)

Also when i try the `monitor swdp_scan` command i get the following 
```
(gdb) monitor swdp_scan
"monitor" command not supported by this target.
(gdb)
```

**Comment by electronut** [comment]
@rishi-electronut please get in touch with Kautham and help out.

**Comment by rishi-electronut** [comment]
@kautham 

Hello Kautham,

Firstly, bumpy is working fine in your system as it is being detected in the Universal Serial Bus devices section.

In order to confirm whether COM ports are being created or not, please remove any other USB device and only plug-in bumpy. Please check if COM ports are created or not.

Secondly, which debugger are you using? If you refer to the instructions, you are supposed to install **GNU ARM Embedded Toolchain** and run 

`arm-none-eabi-gdb`

to run the debugger. Is this being followed?

Also, please send me the screen-shot of the list of commands you are using once you start the debugger.

Thanks.

**Comment by kautham** [comment]
Sorry for the late response i found out the problem.It was a wrong driver installation. I used WinUSB for all the 3 ports instead of using USB Serial driver for the GBD server and UART in the Zadig application.

**Comment by electronut** [comment]
OK, thanks for the update.
